apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: clone-demo
  title: Clone a Git Repository
spec:
  owner: your-org
  type: service
  parameters:
    - title: Repository URL
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: The URL of the GitHub repository to clone.
        args:
          title: Arguments
          type: array
          description: Additional arguments to pass to the Git clone command.
  steps:
    - id: clone-repo
      name: Clone Repository
      action: git:clone
      input:
        repoUrl: 'https://github.com/AmuOta/test'
