apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: clone-orion-api
  title: Clone Orion API Repository
  description: Clones the Orion API GitHub repository into the workspace.
spec:
  owner: backstage-team
  type: service
  parameters:
    - title: Repository Details
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: URL of the GitHub repository to clone.
          default: https://github.com/AmuOta/test
        branch:
          title: Branch Name
          type: string
          description: The branch to clone (default is main).
          default: main
  steps:
    - id: clone-repo
      name: Clone GitHub Repository
      action: git:clone
      input:
        repositoryUrl: ${{ parameters.repoUrl }}
        branchName: ${{ parameters.branch }}
